name: Ircbot
version: @version@
main: com.github.axel012.ircbot.IrcMain
api-version: 1.14
commands:
  start:
    usage: /ircbot:start
    description: Start the irc twitch bot
    aliases: [irsta]
  stop:
    usage: /ircbot:stop
    description: Stop the irc twitch bot
    aliases: [irsto]
  togglechat:
    usage: /ircbot:togglechat
    description: Enable/Disable Twitch chat
    aliases: [tgc]

